# Azure DevOps Pipeline running CI
trigger:
- master

variables:
- template: vars.yml

jobs:
- job: Python_Unit_Tests
  pool:
    name: ARO-CI
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - template: ./templates/template-checkout.yml
  - script: |
      set -xe
      make test-python
      [[ -z "$(git status -s)" ]]
    displayName: '🧪Run Python Unit Tests : $(python.version)'

- job: Golang_Unit_Tests
  pool:
    name: ARO-CI
  steps:
  - template: ./templates/template-checkout.yml
  - script: |
      set -xe
      make test-go
      [[ -z "$(git status -s)" ]]
    displayName: 🧪Run Golang Unit Tests

  - script: |
      go run ./vendor/github.com/jstemmer/go-junit-report/go-junit-report.go < uts.txt > report.xml
      go run ./vendor/github.com/axw/gocov/gocov/*.go convert cover.out > coverage.json
      go run ./vendor/github.com/AlekSi/gocov-xml/gocov-xml.go < coverage.json > coverage.xml
    displayName: ⚙️ Process Reports
    condition: succeededOrFailed()

  - task: PublishTestResults@2
    displayName: 📊 Publish tests results
    inputs:
      testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    displayName: 📈 Publish code coverage
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml
      failIfCoverageEmpty: false
    condition: succeededOrFailed()
