# Azure DevOps Pipeline deploying the azure hosted environment
trigger: none
pr: none

parameters:
- name: environment
  default: ""
- name: LOCATION
  default: ""
- name: CONFIG_FILE_NAME
  default: ""
- name: aro_v4_ci_devops_spn
  default: ""
- name: vso_project_id
  default: ""
- name: vso_config_pipeline_id
  default: ""
- name: vso_deployer_pipeline_id
  default: ""

jobs:
  - template: ./templates/template-job-deploy-azure-env.yml
    parameters:
      environment: $(environment)
      LOCATION: $(LOCATION)
      CONFIG_FILE_NAME: $(CONFIG_FILE_NAME)
      aro-v4-ci-devops-spn: $(aro-v4-ci-devops-spn)
      vso-project-id: $(vso-project-id)
      vso-config-build-id: $(vso-config-build-id)
      vso-deployer-build-id: $(vso-deployer-build-id)
