# Azure DevOps Pipeline running RP e2e and Billing e2e in a single region
variables:
- template: vars.yml
stages:
- template: ./templates/template-rp-and-billing-e2e.yml
  parameters:
    last_stage_of_previous_section: []
    e2e_subscription: $(e2e-subscription)
    aro_v4_e2e_devops_spn: $(aro-v4-e2e-devops-spn)
    billingE2EPipelineName: $(BillingE2EPipelineName)
    billingE2EBranchName: $(BillingE2EBranchName)
    gobin: ${{ variables.GOBIN }}
    gopath: ${{ variables.GOPATH }}
    goroot: ${{ variables.GOROOT }}
    modulePath: ${{ variables.modulePath }}
    locations: $(LOCATION)
