# No PR triggers to run it manually
pr: none
trigger: none

parameters:
- name: vsoConfigBuildID
- name: vsoDeployerBuildID
- name: fullDeploy
  type: boolean
  default: false

stages:
- stage: Deploy_CanarySector
  dependsOn: []
  displayName: 🚀 Deploy Canary Sector
  jobs:
  - template: ./templates/template-job-deploy-azure-env.yml
    parameters:
      environment: RP-Prod-CanarySector
      locations:
      - westcentralus
      - eastus2euap
      configFileName: prod-config.yaml
      azureDevOpsJSONSPN: $(aro-v4-ci-devops-spn)
      vsoProjectID: $(vso-project-id)
      vsoConfigPipelineID: $(vso-config-pipeline-id)
      vsoConfigBuildID: ${{ parameters.vsoConfigBuildID }}
      vsoDeployerPipelineID: $(vso-deployer-pipeline-id)
      vsoDeployerBuildID: ${{ parameters.vsoDeployerBuildID }}
      azureDevOpsE2EJSONSPN: $(aro-v4-e2e-devops-spn)
      e2eSubscription: $(e2e-subscription)
      billingE2EPipelineName: $(billing-e2e-pipeline-name)
      billingE2EBranchName: $(billing-e2e-branch-name)
      fullDeploy: ${{ parameters.fullDeploy }}
- stage: Deploy_LowTrafficSector
  condition: succeededOrFailed()
  dependsOn: [Deploy_CanarySector]
  displayName: 🚀 Deploy Low Traffic Sector
  jobs:
  - template: ./templates/template-job-deploy-azure-env.yml
    parameters:
      environment: RP-Prod-LowTrafficSector
      locations:
      - australiaeast
      - centralindia
      - eastasia
      - japaneast
      - japanwest
      - koreacentral
      configFileName: prod-config.yaml
      azureDevOpsJSONSPN: $(aro-v4-ci-devops-spn)
      vsoProjectID: $(vso-project-id)
      vsoConfigPipelineID: $(vso-config-pipeline-id)
      vsoConfigBuildID: ${{ parameters.vsoConfigBuildID }}
      vsoDeployerPipelineID: $(vso-deployer-pipeline-id)
      vsoDeployerBuildID: ${{ parameters.vsoDeployerBuildID }}
      azureDevOpsE2EJSONSPN: $(aro-v4-e2e-devops-spn)
      e2eSubscription: $(e2e-subscription)
      billingE2EPipelineName: $(billing-e2e-pipeline-name)
      billingE2EBranchName: $(billing-e2e-branch-name)
      fullDeploy: ${{ parameters.fullDeploy }}
- stage: Deploy_USSector
  condition: succeededOrFailed()
  dependsOn: [Deploy_LowTrafficSector]
  displayName: 🚀 Deploy USSector
  jobs:
  - template: ./templates/template-job-deploy-azure-env.yml
    parameters:
      environment: RP-Prod-USSector
      locations:
      - centralus
      - eastus
      - eastus2
      - northcentralus
      - southcentralus
      - westus
      - westus2
      configFileName: prod-config.yaml
      azureDevOpsJSONSPN: $(aro-v4-ci-devops-spn)
      vsoProjectID: $(vso-project-id)
      vsoConfigPipelineID: $(vso-config-pipeline-id)
      vsoConfigBuildID: ${{ parameters.vsoConfigBuildID }}
      vsoDeployerPipelineID: $(vso-deployer-pipeline-id)
      vsoDeployerBuildID: ${{ parameters.vsoDeployerBuildID }}
      azureDevOpsE2EJSONSPN: $(aro-v4-e2e-devops-spn)
      e2eSubscription: $(e2e-subscription)
      billingE2EPipelineName: $(billing-e2e-pipeline-name)
      billingE2EBranchName: $(billing-e2e-branch-name)
      fullDeploy: ${{ parameters.fullDeploy }}
- stage: Deploy_EuropeSector
  dependsOn: [Deploy_USSector]
  condition: succeededOrFailed()
  displayName: 🚀 Deploy EuropeSector
  jobs:
  - template: ./templates/template-job-deploy-azure-env.yml
    parameters:
      environment: RP-Prod-EuropeSector
      locations:
      - canadacentral
      - canadaeast
      - northeurope
      - switzerlandnorth
      - westeurope
      - francecentral
      configFileName: prod-config.yaml
      azureDevOpsJSONSPN: $(aro-v4-ci-devops-spn)
      vsoProjectID: $(vso-project-id)
      vsoConfigPipelineID: $(vso-config-pipeline-id)
      vsoConfigBuildID: ${{ parameters.vsoConfigBuildID }}
      vsoDeployerPipelineID: $(vso-deployer-pipeline-id)
      vsoDeployerBuildID: ${{ parameters.vsoDeployerBuildID }}
      azureDevOpsE2EJSONSPN: $(aro-v4-e2e-devops-spn)
      e2eSubscription: $(e2e-subscription)
      billingE2EPipelineName: $(billing-e2e-pipeline-name)
      billingE2EBranchName: $(billing-e2e-branch-name)
      fullDeploy: ${{ parameters.fullDeploy }}
- stage: Deploy_ROWSector
  dependsOn: [Deploy_EuropeSector]
  condition: succeededOrFailed()
  displayName: 🚀 Deploy ROWSector
  jobs:
  - template: ./templates/template-job-deploy-azure-env.yml
    parameters:
      environment: RP-Prod-ROWSector
      locations:
      - brazilsouth
      - southeastasia
      - southafricanorth
      - uaenorth
      - uksouth
      - ukwest
      configFileName: prod-config.yaml
      azureDevOpsJSONSPN: $(aro-v4-ci-devops-spn)
      vsoProjectID: $(vso-project-id)
      vsoConfigPipelineID: $(vso-config-pipeline-id)
      vsoConfigBuildID: ${{ parameters.vsoConfigBuildID }}
      vsoDeployerPipelineID: $(vso-deployer-pipeline-id)
      vsoDeployerBuildID: ${{ parameters.vsoDeployerBuildID }}
      azureDevOpsE2EJSONSPN: $(aro-v4-e2e-devops-spn)
      e2eSubscription: $(e2e-subscription)
      billingE2EPipelineName: $(billing-e2e-pipeline-name)
      billingE2EBranchName: $(billing-e2e-branch-name)
      fullDeploy: ${{ parameters.fullDeploy }}
