on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - uses: actions/checkout@v1
    - run: |
        go get github.com/alvaroloes/enumer
        go get github.com/jim-minter/go-cosmosdb/cmd/gencosmosdb
        
        go generate ./...
        go build ./...
        go test ./...
        
        [[ -z $(git status -s) ]]
